
class Vector2:
    x: float
    y: float
    def __init__(self, x: float = 0.0, y: float = 0.0): ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __add__(self, other) -> 'Vector2': ...
    def __sub__(self, other) -> 'Vector2': ...
    def __mul__(self, scalar: float) -> 'Vector2': ...
    def __truediv__(self, scalar: float) -> 'Vector2': ...
    def __eq__(self, other) -> bool: ...
    def __repr__(self) -> str: ...
    
    def dot(self, other: 'Vector2') -> float: ...